### ISSUE TITLE
Unhandled Promise

### ISSUE THREAD

**Issue by Illizion** [eslachance/enmap-mongo#1]
Heres the long story short:
```
(node:5654) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [minimebot-avzam.gcp.mongodb.net:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND minimebot-avzam.gcp.mongodb.net minimebot-avzam.gcp.mongodb.net:27017]

at Pool.<anonymous> (/rbd/pnpm-volume/5470c346-4081-4729-9bec-e01121a104fb/node_modules/.registry.npmjs.org/mongodb-core/3.0.9/node_modules/mongodb-core/lib/topologies/server.js:505:11)

    at emitOne (events.js:116:13)

    at Pool.emit (events.js:211:7)

    at Connection.<anonymous> (/rbd/pnpm-volume/5470c346-4081-4729-9bec-e01121a104fb/node_modules/.registry.npmjs.org/mongodb-core/3.0.9/node_modules/mongodb-core/lib/connection/pool.js:329:12)

    at Object.onceWrapper (events.js:317:30)

    at emitTwo (events.js:126:13)

    at Connection.emit (events.js:214:7)

    at Socket.<anonymous> (/rbd/pnpm-volume/5470c346-4081-4729-9bec-e01121a104fb/node_modules/.registry.npmjs.org/mongodb-core/3.0.9/node_modules/mongodb-core/lib/connection/connection.js:245:50)

    at Object.onceWrapper (events.js:315:30)

    at emitOne (events.js:116:13)

(node:5654) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:5654) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


/rbd/pnpm-volume/5470c346-4081-4729-9bec-e01121a104fb/node_modules/.registry.npmjs.org/mongodb/3.0.10/node_modules/mongodb/lib/mongo_client.js:794

          throw err;

          ^

MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]

at Pool.<anonymous> (/rbd/pnpm-volume/5470c346-4081-4729-9bec-e01121a104fb/node_modules/.registry.npmjs.org/mongodb-core/3.0.9/node_modules/mongodb-core/lib/topologies/server.js:505:11)

    at emitOne (events.js:116:13)

    at Pool.emit (events.js:211:7)

    at Connection.<anonymous> (/rbd/pnpm-volume/5470c346-4081-4729-9bec-e01121a104fb/node_modules/.registry.npmjs.org/mongodb-core/3.0.9/node_modules/mongodb-core/lib/connection/pool.js:329:12)

    at Object.onceWrapper (events.js:317:30)

    at emitTwo (events.js:126:13)

    at Connection.emit (events.js:214:7)

    at Socket.<anonymous> (/rbd/pnpm-volume/5470c346-4081-4729-9bec-e01121a104fb/node_modules/.registry.npmjs.org/mongodb-core/3.0.9/node_modules/mongodb-core/lib/connection/connection.js:245:50)

    at Object.onceWrapper (events.js:315:30)

    at emitOne (events.js:116:13)
```
it won't connect to my remote MongoDB instance
for your info:
i am hosting on glitch and i want to do the points guide from [An Idiots Guide](https://anidiots.guide/) and now my bot won't even run because it's throwing an error

**Comment by Illizion** [comment]
forget it. i fixed it 🤦‍♂️
